# Title of your homepage
title: BloxTech Applications • Changelog #(required)

# Website Description for search engines (optional)
description: "Keep yourself up to date with new features at BloxTech Applications"

# replace this word in navigation bar. Ex: Productnews, ChangeLog, Updates
heading: Changelog # (optional)

# absolute or relative path of logo
logo: https://bloxtech.tech/admin/applications/assets/img/Untitled.png #(required)

# Your Product's Website
website: https://bloxtech.tech # (required)

# the base hostname & protocol for your site, 
# e.g. https://updates.changelog.site
# Note Don't put trailing slash https://updates.changelog.site/
url: "https://changelog.bloxtech.tech"  # (required)

baseurl: '' # optional


# Github username/repo where your code is hosted.
github: chrissie1234/changelog # (required)

# Global site tag (gtag.js) - Google Analytics e.g. UA-MYANALYTICS
analytics:  #(recommended)

# Allow users to comment via facebook
fb-comment: false

# Allow search engines to index your changelog website
allow-searchengine: true #optional


# Do not change anything below this if you don't know Jekyll

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets"
    values:
      sitemap: false 
  -
    scope:
      path: "admin"
    values:
      sitemap: false 

permalink: /:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir:         _sass
  style:            compressed


plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap

pagination:
  enabled: true
  per_page: 5
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
